# Generated by Django 2.0.13 on 2019-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
